### ISSUE TITLE
Running the simulation

### ISSUE THREAD

**Issue by b-safwat** [pengyuan-zhou/AICP#1]
I am new to vein and I am trying to run the simulation. I copied the files both examples and modules in the corresponding directories for the default veins project. However, I still cannot make it work. I would use any tips or advice, thanks!

More explicitly, I am getting this error: 
A runtime error occurred: 

Unknown parameter 'frameErrorRate' -- in module
(veins::Mac1609_4) RSUExampleScenario.rsu[0].nic.mac1609_4
(id=13), during network initialization

**Comment by pengyuan-zhou** [comment]
Hi, did you rebuild after copying the files?
